# Generated by Django 2.2.3 on 2019-08-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_hoteles_informacion_mapa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hoteles',
            new_name='Hotel',
        ),
        migrations.RenameModel(
            old_name='Informacion',
            new_name='Info',
        ),
    ]
