# Generated by Django 2.2.3 on 2019-08-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190825_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapa',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
