# Generated by Django 2.2.3 on 2019-09-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190825_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('name',)},
        ),
        migrations.AlterIndexTogether(
            name='info',
            index_together={('id', 'slug')},
        ),
    ]
