# Generated by Django 2.2.3 on 2019-10-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190929_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='imagesecond',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info',
            name='imagethird',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
