# Generated by Django 2.2.3 on 2019-10-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20191005_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='descriptionsecond',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='descriptionthird',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='imagefourth',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
