# Generated by Django 2.2.3 on 2019-10-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20191006_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justimages',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='justimages',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
