# Generated by Django 2.2.3 on 2019-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20191006_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoneimage', models.ImageField(default='img', upload_to='products/%Y/%m/%d')),
                ('name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
