# Generated by Django 2.2.3 on 2019-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_justimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justimages',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='justimages',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
