# Generated by Django 2.2.3 on 2019-10-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20191006_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JustImages',
        ),
    ]
