# Generated by Django 2.2.3 on 2019-10-06 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20191006_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='justimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.JustImages'),
        ),
    ]
